import time
from threading import Thread

subjects = ["DBMS", "OOPs", "OS", "NS", "CN", "ISC"]

def display(subs):
    for sub in subs:
        print("Sub:", sub, "This line is executing by t1 thread")
        time.sleep(1.5)


class myThread(Thread):
    def __init__(self, subs):
        super().__init__()
        self.subs = subs

    def run(self):
        display(self.subs)
        # for sub in subjects:
        #     print("Sub:", sub, end=", ")
        #     time.sleep(1)
        #     print("This line is executing by t1 thread")
        
        self.newList = self.subs
        self.newList.append("MIT")
        
t1 = myThread(subjects)
t1.start()

for i in subjects:
    time.sleep(0.4)
    print("This line is executing by Main thread")

time.sleep(10)
print(t1.newList)  # We can access the data generated by thread