# Generated by Django 5.2.11 on 2026-02-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('dept', models.CharField(choices=[('CSE', 'Computer Science'), ('EE', 'Electrical'), ('ECE', 'Electronic and Communication'), ('MSC', 'Master of Science')])),
                ('birth_date', models.DateField()),
                ('img', models.ImageField(upload_to='nalles_img/')),
            ],
        ),
    ]
