# Generated by Django 5.2.11 on 2026-02-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nalles',
            old_name='img',
            new_name='image',
        ),
    ]
