# Generated by Django 5.2.11 on 2026-02-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_rename_img_nalles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='nalles',
            name='song',
            field=models.TextField(default='-'),
        ),
    ]
