# Generated by Django 5.2.11 on 2026-02-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_nalles_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='nalles',
            name='song_url',
            field=models.TextField(default='-'),
        ),
    ]
